projecthamster/hamster-lib

hamsterlib/storage.py
tests/hamsterlib/test_storage.py

This PR turns our method for stoping 'ongoing facts' into a public API call.
Closes #61

[#61] Made ``_stop_tmp_fact`` a public method.

---

hamsterlib/storage.py
tests/hamsterlib/test_storage.py

This PR adds a ``get_tmp_fact`` method to our fact-manager class.
This allows clients to easily retrieve the ongoing fact if there is one. We raises an ``KeyError`` otherwise.
Closes: #60

[#60] Add ``get_tmp_fact`` fact-manager method.

---

hamsterlib/storage.py
tests/hamsterlib/test_storage.py

This PR provides a ``cancel_tmp_fact`` method to our fact-manager class.
This allows clients to stop an ongoing fact without storing it to the backend.
Closes: #59

[#59] Add ``cancel_tmp_fact`` fact-manager method.

---

hamsterlib/__init__.py
hamsterlib/backends/sqlalchemy/storage.py
hamsterlib/objects.py
hamsterlib/storage.py

This PR greatly improves logging of our storage related functionalities.
Whist the exact messages can certainly be improved still, at least now we make sure that exceptions are logged on the ``error`` level, while also providing (very verbose) ``debug`` logging upon method calling and often even their success.
All a client needs to do now is to attach a proper handler to ``sore.logger``, specify some format and loglevel and we are ready to go.
Also:
* Removed tags from a ``Facts`` representation as we currently do not support them.
Closes: #21

[21] storage operations write to store.logger

---

docs/usage.rst
hamsterlib/storage.py
tests/conftest.py
tests/hamsterlib/test_storage.py

This PR introduces the notion of a *minimum delta* for facts.
For this purpose a new config-key ``fact_min_delta`` has been introduced. Facts with a delta smaller than this are not to be stored by the backend. Instead we raise a ``ValueError``.
This is implemented by adjusting the ``save`` method of our fact manager.
Closes: #75

[75] Treshold for ongoing facts

---

HISTORY.rst
hamster_lib/backends/sqlalchemy/storage.py

Besides the incomplete docstring for ``FactManager._get_all`` we also
fixed lots of reference to ``hamster-lib`` that should be
``hamster_lib``.
Closes: #136

Fix docstring in backends.sqlalchemy.storage

---

setup.cfg

This PR stops bumpversion from automatically creating tags.
Closes: #126

Stop bumpversion creating tags

---

hamster_lib/backends/sqlalchemy/storage.py
hamster_lib/objects.py
tests/backends/sqlalchemy/test_storage.py
tests/hamster_lib/test_objects.py

As ``Fact.serialized_name`` is not realy needed in our rewrite we remove
it from the ``Fact`` class. This however meant that we had to transfer
some of its string construction logic to ``Fact.__str__``.
In order to avoid duplicating the effort with regards to
``Fact.__repr__`` and because issue #131 will take care of it in a
holistic way anyway we removed ``Fact.__repr__`` for now ass well.
Tests have been adjusted accordingly.
Note:
* Our Fact class now provides a proper text representation even if it
misses any ``Fact.start`` value.
* This PR includes a minor refactoring commit as well as an additional test case. Both are added as seperate commits.
Closes: #146

Remove 'Fact.serialized_name' property and __repr__

---

tests/backends/sqlalchemy/factories.py
tests/hamster_lib/factories.py

This removes the naive and error prone usage of stand alone ``faker``
calls in our factories for the proper ``factory.Faker`` ones. Those
basicly wrap our calls in ``LazyAttributes``. Where we generate random
data from non-faker sources, e.g. ``fauxfactory`` we make sure to do the
wrapping ourselfs.
Closes: #149

Use factory.Faker only and wrap 'fauxfactory' (#149)

---

hamster_lib/objects.py
tests/conftest.py
tests/hamster_lib/test_objects.py

This PR introduces a naive ``__hash__`` implementation for classes in ``hamster_lib.objects`` in order to make sure they are ``hashable``.
As a side effect we also include a commit that changes ``Fact.tags`` to a ``set`` (from being a ``list`` before). Although tags have not actually been implemented it seems semantically more correct.
Closes: #137

[137] Make objects hashable

---

hamster_lib/helpers.py
hamster_lib/objects.py
setup.py
tests/backends/sqlalchemy/test_storage.py
tests/hamster_lib/test_objects.py

This pr adds dedicated and refactored ``__repr__`` methods to our ``hamsterlib.objects`` classes.
Those make sure that instances can be represented even in non unicode environments.
Closes: #131

[131] Add consistent __repr__ methods

---

hamster_lib/backends/sqlalchemy/storage.py
hamster_lib/lib.py
tests/backends/sqlalchemy/conftest.py
tests/backends/sqlalchemy/test_storage.py

Running python 2, it apears SQLAlchemy is not fully capable to handle
unicode strings as urls. While they can be passed and will be processed
(correctly as far as we can tell) there are issues with 'representing'
an ``Engine`` or ``sqlalchemy.engine.url.URL``. As far as we understand,
their ``repr()`` call will naivly construct a ``str`` from its various
components. If any of those substrings (like the URL) happens to be an
unicode string, this will fail if it can not be ascii-decoded.
SQLAlchemy should propably call repr(url) instead.
For now, this commit just avoids the problem entirely by amending the
triggering log message not to render a string representation of the
created engine. A proper solution would probably be to write a custom
wrapper function that handles Engine …

[#130]Add test and fix for SA Engine repr failure

---

hamster_lib/backends/sqlalchemy/storage.py
hamster_lib/storage.py
setup.cfg
tests/backends/sqlalchemy/test_storage.py
tests/conftest.py

This commit removes ``FactManager._timeframe_is_free``. It's only
difference to ``FactManager._get_all()`` was that it would consider
facts that are only partially within the given timeframe. This behavior
has been incorporated into ``_get_all()`` instead. By passing
``partial=True`` as a ``kwarg`` is the method will return all facts
within the timeframe that either start or end in it.
This can then be used to not only check if a timeframe is free but (in
case of an ``_update`` if the only fact blocking it is the one to be
updated.
We also used the opportunity to provide more and better tests.
Closes: #138

Refactor ``FactManager._get_all()`` and ``_timeframe_is_free()``

---

hamster_lib/backends/sqlalchemy/storage.py
hamster_lib/storage.py
tests/backends/sqlalchemy/test_storage.py

This commit refactors the manager method in order to allow it to
retrieve *all* stored activities. Previously ``categories=None``
translated to fetching all uncategorized categories. We now added the
option to pass ``categories=False`` in order to fetch all activities.
Closes: #134

Improve ActivityManager.get_all() (#134)

---

docs/labels.rst
docs/styleguide.rst

This commits provides a first go at a basic styleguide for the project. This will most likly require more work in order to provide a clearer structure. As a seperate page we provide an overview over all labels used by the project.
Closes: #76

Add styleguide (#76)

---

.editorconfig

In particular, this PR makes sure that we use a indentation of ``3``.

Add ``rst`` specific settings to editorconfig

---

.travis.yml
CONTRIBUTING.rst
README.rst
docs/conf.py
docs/index.rst
docs/labels.rst
docs/notes.rst
docs/packaging.rst
docs/styleguide.rst
docs/usage.rst
hamster_lib/backends/sqlalchemy/storage.py
hamster_lib/objects.py
tox.ini

This PR add the ``docs`` test environment to our refular tox and Travis testsuite.
As a preperation to do this this, PR also includes commits fixing minor documentation errors and warning.
Closes: #165

Add doc testenv to tox defaults and travis (#165)

---

docs/conf.py
tox.ini

Some urls don't play nice with linkchecker due to ssl issues. Until this has been sorted out in greater details they have been placed on a *ignore list* in ``docs.conf.py``.
Closes: #172

[#172] Add linkchecker to 'docs' testenvironment

---

.travis.yml
tox.ini

Make travis respect python versions per environment
By editing the new section ``tox:travis`` in ``tox.ini`` it is easily
possible to transparently control which environment is run under which
python version.
This also means that the ``basepython`` value for tox environments is ignored.
Closes: #171

[#171]Use 'tox-travis'

---

Makefile
requirements/dev.pip

Commit a7c731e82579882f93c78fdd7ad8d61bfeae0a27 did a uncomplete job
changes all references to requirements/*.txt to its new *.pip
counterparts. This is remedied by this commit.

Fix broken requirements/*.pip

---

hamster_lib/helpers/config_helpers.py
tests/helpers/test_config_helpers.py

The changed helper method limits itself to retrieval of the configparser instance if a file is present.
Otherwise it lets the caller know. It no longer ensures that a default config is written and returned. This is the clients task if it wishes this.
Closes: #197

[#197] Changed 'get_config' helper to 'load_config'

---

hamster_lib/lib.py
tests/hamster_lib/test_lib.py

This PR adds a dedicated method to update a controlers config.
This method is in charge of applying the new config to the controler.
Right now that means updating the config attribute and constructing a
new store. This should not be an issue as the store itself is not
supposed to store any state to begin with.
Closes: #190

[#190] Add 'HamsterControl.update_config' method

---

docs/conf.py
hamster_lib/__init__.py
hamster_lib/backends/sqlalchemy/__init__.py
hamster_lib/backends/sqlalchemy/objects.py
hamster_lib/backends/sqlalchemy/storage.py
hamster_lib/objects.py
hamster_lib/storage.py
setup.py
tests/backends/sqlalchemy/conftest.py
tests/backends/sqlalchemy/factories.py
tests/backends/sqlalchemy/test_objects.py
tests/backends/sqlalchemy/test_storage.py
tests/conftest.py
tests/hamster_lib/conftest.py
tests/hamster_lib/factories.py
tests/hamster_lib/test_objects.py
tests/hamster_lib/test_storage.py
tests/helpers/test_helpers.py

This PR adds tags as optional information for facts to our ontology.
Facts can be used to add additional context to individual facts.
For that purpose a new ``objects.Tag`` has been added as well as a
corresponding SQLAlchemy class.
On the ``hamster`` level, ``Fact.tags`` is a set of ``objects.Tag``
instances. When a ``Fact`` is 'tupleized' this set is turned into a
``frozenset`` to be immutable.
On the SQLAlchemy level a intermediate table ``facttags`` has been
added.
Factories and fixtures have been adjusted accordingly to feature
radomized tags by default.
Because most sqlbackend related test do test that the db_instance
against the passed hamster instance it offen sufficed to make sure that
the used instance now features tags. For ``FactManager.__add``,`` __update``
and ``remove`` we …

[#127] Support Tags

---

hamster_lib/backends/sqlalchemy/storage.py
hamster_lib/helpers/time.py
hamster_lib/objects.py
tests/backends/sqlalchemy/test_storage.py
tests/hamster_lib/conftest.py
tests/hamster_lib/test_objects.py
tests/helpers/test_time.py
tox.ini

This PR changes the way timeinfo is extracted and completed from a
``raw fact``.
The old ``time.parse_time_info`` helper function has been replaced by
``extract_time_info``. This function takes a raw fact string and appies
our expectation to timeinfo formatting via regexes.
The procedure looks more cumbersome than the original version *but* is
more strict/accurate. If someone with more regex mojo feels like
improving it, it shall be greatly appreciated.
Instead of using one regex with ``?`` quantifiers we use a multi stepped
approach to first check for a start time and only apply additional
filters to check for end time information. One direct consequence is
that *anything* not matching our expected format will be considered part
of the 'rest'/'activity'. Something some users expressed …

[#198] Refactor timeinfo parsing

---

tests/backends/sqlalchemy/factories.py

Some factories do not use simple attributes but function calls
to generate their names. In those cases ``factory.Faker`` (which usually
handles all the ``LazyAttribute`` wrapping) is the wrong choice and we
need to use a regular ``faker.Faker()`` instead.
Fixes: LIB-205

[LIB-205] Fix fakerusage in sqlalchemy backend tests.

---

hamster_lib/helpers/time.py
tests/helpers/test_time.py

This PR adds a very basic sanity check for the result of
``helpers.time.complete_timeframe``. A new ``validate_start_end_range``
function is used to make sure that ``start < end``.
It also includes two minor cleanup commits.
Closes: LIB-30

[LIB-30] Validate 'helpers.time.complete_timeframe'

---

docs/usage.rst
hamster_lib/helpers/time.py
hamster_lib/lib.py
hamster_lib/objects.py
tests/hamster_lib/conftest.py
tests/hamster_lib/test_lib.py

This commit replaces incorrectly spelled 'controler' with 'controller' throughout the codebase. This is mostly cosmetic change, only tests and comments were affected.
Fixes: LIB-220

[LIB-220] Replace 'controler' with 'controller'

---

hamster_lib/reports.py
tests/hamster_lib/test_reports.py

We streamline our attribute names for the generate XML in order to more
clearly reflect the attributes nature as we no longer need to care about
*legacy hamster*.
A separate commit fixes some minor typos.
Closes: [LIB-109](https://projecthamster.atlassian.net/browse/LIB-109)

[LIB-109] Refactor XMLWriter attributes

---

hamster_lib/objects.py
tests/hamster_lib/test_objects.py

This should be more in line with the format used by ``parse_raw_fact``.
Please note that still start and end are seperated by ``to`` here while
``parse_raw_fact`` uses ``-``.
Closes: [LIB-211](https://projecthamster.atlassian.net/browse/LIB-211)

[LIB-211] Change dateformat for str/repr(fact) to iso

---

hamster_lib/storage.py
tests/conftest.py
tests/hamster_lib/test_storage.py

This PR introduces a new ``update_tmp_fact`` method to the fact
manager. This method allows clients to modify attributes of an existing
ongoing fact.
This PR also improves the ``new_fact_values`` fixture so it now is
able to accept facts with ``Fact.end=None``.
Closes: LIB-132

[LIB-132] Add 'BaseFactManager.update_tmp_fact'

---

Makefile

Instead of using our own environment variable to pass additional parameters to individual test runs this PR switches to using pytests own ``PYTEST_ADDOPTS`` variable.
Closes: [LIB-218](https://projecthamster.atlassian.net/browse/LIB-218)

[LIB-218] Use 'PYTEST_ADDOPTS' instead of 'TEST_ARGS'

---

hamster_lib/storage.py
tests/hamster_lib/test_storage.py

Clients may add an optional ``end_hint`` (``datetime`` or ``timedelta``) parameter when stopping an
*ongoing fact* to influence the computed end value for the fact to be
saved.
Closes: [LIB-129](https://projecthamster.atlassian.net/browse/LIB-129)

[LIB-129] Add 'offset' parameter to 'stop_tmp_fact'

---

hamster_lib/storage.py
tests/backends/sqlalchemy/test_objects.py
tests/hamster_lib/test_storage.py

This PR adds a test for the backends  ``Tag.as_hamster`` method to make sure conversion works as expected.
Closes: LIB-217

[LIB-217] Extend SQLAlchemy backend test coverage for tags

---

hamster_lib/helpers/config_helpers.py
tests/helpers/conftest.py
tests/helpers/test_config_helpers.py

This commit cleans up our existing config related helper code as well as
providing a additional more unified interfaces to deal with storage and
retrieval of backend config information.
As mentioned in the module documentation, clients main way to make use
of those helpers is to call upon ``load_config_file`` and
``write_config_file``.
In most function signatures we changed ``appname`` for ``appdirs`` as
there is no point instantiating appdirs within each function anew.
Instead we create one appdir instance holding all the relevant
informantion and pass this allong.
Unlike before ``load_config_file`` will now allways return a
``ConfigParser`` instance, either from an existing config file or one
writen to a new config file using the fallback strategy. That also
means that calling …

[LIB-235] Refactor 'config_helpers'

---

codecov.yml
docs/packaging.rst
hamster_lib/helpers/time.py
hamster_lib/objects.py
tests/hamster_lib/conftest.py
tests/hamster_lib/test_objects.py

[LIB-250] Remove check for start-timeinfo when validating timeframes
